require: rubocop-rails
AllCops:
  Exclude:
    - db/ELASTIC
    - db/PGSQL
    - db/REDIS
    - db/schema.rb
    - tmp
Style/FrozenStringLiteralComment:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - Gemfile
    - Rakefile
    - test/test_helper.rb
    - config/boot.rb
    - config/importmap.rb
    - config/application.rb
    - config/initializers/assets.rb
    - config/environments/test.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - app/mailers/application_mailer.rb
Naming/FileName:
  Exclude:
    - config/_PUMA.rb
    - config/_SCHEDULE.rb
    - config/initializers/_CHEWY.rb
    - config/initializers/_CONFIG.rb
    - config/initializers/_REDIS.rb
    - config/initializers/_SIDEKIQ.rb
Style/SymbolArray:
  Exclude:
    - config/initializers/filter_parameter_logging.rb
Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb
Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb
Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - Gemfile
Rails/Output:
  Exclude:
    - db/seeds.rb
    - app/jobs/example_job.rb
    - app/models/currency_rate.rb
    - config/environments/development.rb
    - config/initializers/_CHEWY.rb
    - config/initializers/_CONFIG.rb
    - config/initializers/_REDIS.rb
    - config/initializers/_SIDEKIQ.rb
Metrics/MethodLength:
  Exclude:
    - app/controllers/demo_controller.rb
Style/GlobalVars:
  Exclude:
    - config/initializers/_REDIS.rb
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
  Exclude:
    - config/environments/development.rb
