version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.2.1
  pre_build:
    commands:
      - gem install bundler
      - bundle install
  build:
    commands:
      - bin/setup
      - bundle exec rake db:migrate
      - bundle exec rake spec
artifacts:
  files:
    - '**/*'